
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gptc
 */
public class luctreg extends javax.swing.JFrame {

    /**
     * Creates new form luctreg
     */
    public luctreg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        luctname = new javax.swing.JTextField();
        luctmale = new javax.swing.JRadioButton();
        luctfemale = new javax.swing.JRadioButton();
        luctmail = new javax.swing.JTextField();
        luctpass = new javax.swing.JPasswordField();
        plus = new javax.swing.JCheckBox();
        dip = new javax.swing.JCheckBox();
        bt = new javax.swing.JCheckBox();
        mt = new javax.swing.JCheckBox();
        subb = new javax.swing.JComboBox<>();
        luctsubmit = new javax.swing.JButton();
        luctexit = new javax.swing.JButton();
        luctreset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        luctid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NAME");

        jLabel4.setText("GENDER");

        jLabel5.setText("EMAIL");

        jLabel6.setText("PASSWORD");

        jLabel8.setText("QUALIFICATION");

        jLabel9.setText("SUBJECT");

        luctname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luctnameActionPerformed(evt);
            }
        });

        buttonGroup1.add(luctmale);
        luctmale.setText("Male");
        luctmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luctmaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(luctfemale);
        luctfemale.setText("Female");
        luctfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luctfemaleActionPerformed(evt);
            }
        });

        luctmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luctmailActionPerformed(evt);
            }
        });

        plus.setText("+2");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        dip.setText("Diploma");
        dip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dipActionPerformed(evt);
            }
        });

        bt.setText("Btech");

        mt.setText("Mtech");
        mt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtActionPerformed(evt);
            }
        });

        subb.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        subb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "CSH", "DS", "DC", "SA", " ", " " }));
        subb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subbActionPerformed(evt);
            }
        });

        luctsubmit.setText("REGISTER");
        luctsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luctsubmitActionPerformed(evt);
            }
        });

        luctexit.setText("EXIT");

        luctreset.setText("RESET");

        jLabel2.setText("LUCT ID");

        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(luctmale)
                                .addGap(37, 37, 37)
                                .addComponent(luctfemale))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(luctsubmit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dip)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(luctreset))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mt))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(luctname, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addComponent(luctmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(luctid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(luctpass, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(176, 176, 176)
                                .addComponent(luctexit))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(luctexit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luctname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luctmale)
                    .addComponent(luctfemale)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(luctmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(luctid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(luctpass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(plus)
                    .addComponent(dip)
                    .addComponent(bt)
                    .addComponent(mt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(subb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luctsubmit)
                    .addComponent(luctreset))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luctmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luctmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luctmailActionPerformed

    private void luctnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luctnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luctnameActionPerformed
    String n1,n2,n3,n4;
    String gender;
    private void luctmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luctmaleActionPerformed
      gender="Male";  // TODO add your handling code here:
    }//GEN-LAST:event_luctmaleActionPerformed

    private void luctfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luctfemaleActionPerformed
     gender="Female";     // TODO add your handling code here:
    }//GEN-LAST:event_luctfemaleActionPerformed

    private void subbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subbActionPerformed
    String qa=""; String subject;
    private void luctsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luctsubmitActionPerformed
    n1=luctname.getText();
    n2=luctmail.getText();
    n3=luctid.getText();
    n4=luctpass.getText();
   Object sub= subb.getSelectedItem();
    subject=String.valueOf(sub);
    
    if(plus.isSelected())
    {
        qa=qa+" Plus Two";    }
    if(dip.isSelected())
    {
      qa=qa+"Diploma";
    }//GEN-LAST:event_luctsubmitActionPerformed
      if(bt.isSelected())
    {
      qa=qa+"B tech";
    }                              
      if(mt.isSelected())
    {
      qa=qa+"M tech";
    }
    try
        {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/mathews","mathews","1234");
            Statement st=con.createStatement();
           
           
            String sqlInsert="insert into luctreg values('"+n1+"','"+gender+"','"+n2+"','"+n3+"','"+n4+"','"+subject+"','"+qa+"')";
              
              int x=st.executeUpdate(sqlInsert);
              if(x!=0)
              {
                  JOptionPane.showMessageDialog(null,"Sucess");
              }
           
           }
        catch(Exception e)
        {
             System.out.println(e);
        }
         
     
                                      
     
    }
    private void dipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dipActionPerformed

    private void mtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mtActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new luctreg().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox dip;
    private javax.swing.JTextArea display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luctexit;
    private javax.swing.JRadioButton luctfemale;
    private javax.swing.JTextField luctid;
    private javax.swing.JTextField luctmail;
    private javax.swing.JRadioButton luctmale;
    private javax.swing.JTextField luctname;
    private javax.swing.JPasswordField luctpass;
    private javax.swing.JButton luctreset;
    private javax.swing.JButton luctsubmit;
    private javax.swing.JCheckBox mt;
    private javax.swing.JCheckBox plus;
    private javax.swing.JComboBox<String> subb;
    // End of variables declaration//GEN-END:variables
}
